export const SEED_MATERIALS = [
  // EQUIPMENT
  { name: '1.5 Ton 14 SEER2 AC Condenser', category: 'Equipment', unit: 'Each', defaultCost: 720, isActive: true },
  { name: '2 Ton 14 SEER2 AC Condenser', category: 'Equipment', unit: 'Each', defaultCost: 850, isActive: true },
  { name: '2.5 Ton 14 SEER2 AC Condenser', category: 'Equipment', unit: 'Each', defaultCost: 950, isActive: true },
  { name: '3 Ton 14 SEER2 AC Condenser', category: 'Equipment', unit: 'Each', defaultCost: 1050, isActive: true },
  { name: '3.5 Ton 14 SEER2 AC Condenser', category: 'Equipment', unit: 'Each', defaultCost: 1150, isActive: true },
  { name: '4 Ton 14 SEER2 AC Condenser', category: 'Equipment', unit: 'Each', defaultCost: 1250, isActive: true },
  { name: '5 Ton 14 SEER2 AC Condenser', category: 'Equipment', unit: 'Each', defaultCost: 1500, isActive: true },
  { name: '1.5 Ton Air Handler', category: 'Equipment', unit: 'Each', defaultCost: 480, isActive: true },
  { name: '2 Ton Air Handler', category: 'Equipment', unit: 'Each', defaultCost: 550, isActive: true },
  { name: '2.5 Ton Air Handler', category: 'Equipment', unit: 'Each', defaultCost: 600, isActive: true },
  { name: '3 Ton Air Handler', category: 'Equipment', unit: 'Each', defaultCost: 650, isActive: true },
  { name: '3.5 Ton Air Handler', category: 'Equipment', unit: 'Each', defaultCost: 700, isActive: true },
  { name: '4 Ton Air Handler', category: 'Equipment', unit: 'Each', defaultCost: 750, isActive: true },
  { name: '5 Ton Air Handler', category: 'Equipment', unit: 'Each', defaultCost: 900, isActive: true },
  { name: '1.5 Ton Heat Pump Condenser 14 SEER2', category: 'Equipment', unit: 'Each', defaultCost: 950, isActive: true },
  { name: '2 Ton Heat Pump Condenser 14 SEER2', category: 'Equipment', unit: 'Each', defaultCost: 1100, isActive: true },
  { name: '2.5 Ton Heat Pump Condenser 14 SEER2', category: 'Equipment', unit: 'Each', defaultCost: 1225, isActive: true },
  { name: '3 Ton Heat Pump Condenser 14 SEER2', category: 'Equipment', unit: 'Each', defaultCost: 1350, isActive: true },
  { name: '3.5 Ton Heat Pump Condenser 14 SEER2', category: 'Equipment', unit: 'Each', defaultCost: 1475, isActive: true },
  { name: '4 Ton Heat Pump Condenser 14 SEER2', category: 'Equipment', unit: 'Each', defaultCost: 1600, isActive: true },
  { name: '5 Ton Heat Pump Condenser 14 SEER2', category: 'Equipment', unit: 'Each', defaultCost: 1900, isActive: true },
  { name: '2 Ton Heat Pump Air Handler w/ 5kW Heat Strip', category: 'Equipment', unit: 'Each', defaultCost: 680, isActive: true },
  { name: '3 Ton Heat Pump Air Handler w/ 5kW Heat Strip', category: 'Equipment', unit: 'Each', defaultCost: 750, isActive: true },
  { name: '3 Ton Heat Pump Air Handler w/ 10kW Heat Strip', category: 'Equipment', unit: 'Each', defaultCost: 820, isActive: true },
  { name: '4 Ton Heat Pump Air Handler w/ 10kW Heat Strip', category: 'Equipment', unit: 'Each', defaultCost: 900, isActive: true },
  { name: '5 Ton Heat Pump Air Handler w/ 15kW Heat Strip', category: 'Equipment', unit: 'Each', defaultCost: 1050, isActive: true },
  { name: '9,000 BTU Mini-Split Single Zone', category: 'Equipment', unit: 'Each', defaultCost: 750, isActive: true },
  { name: '12,000 BTU Mini-Split Single Zone', category: 'Equipment', unit: 'Each', defaultCost: 900, isActive: true },
  { name: '18,000 BTU Mini-Split Single Zone', category: 'Equipment', unit: 'Each', defaultCost: 1100, isActive: true },
  { name: '24,000 BTU Mini-Split Single Zone', category: 'Equipment', unit: 'Each', defaultCost: 1350, isActive: true },
  { name: '36,000 BTU Mini-Split Single Zone', category: 'Equipment', unit: 'Each', defaultCost: 1600, isActive: true },
  { name: '9,000 BTU Mini-Split Multi-Zone Head', category: 'Equipment', unit: 'Each', defaultCost: 380, isActive: true },
  { name: '12,000 BTU Mini-Split Multi-Zone Head', category: 'Equipment', unit: 'Each', defaultCost: 420, isActive: true },
  { name: '18,000 BTU Mini-Split Multi-Zone Head', category: 'Equipment', unit: 'Each', defaultCost: 520, isActive: true },
  { name: 'Multi-Zone Mini-Split Outdoor Unit (2 Zone)', category: 'Equipment', unit: 'Each', defaultCost: 1200, isActive: true },
  { name: 'Multi-Zone Mini-Split Outdoor Unit (3 Zone)', category: 'Equipment', unit: 'Each', defaultCost: 1500, isActive: true },
  { name: 'Multi-Zone Mini-Split Outdoor Unit (4 Zone)', category: 'Equipment', unit: 'Each', defaultCost: 1800, isActive: true },
  { name: '80% AFUE 40k BTU Gas Furnace', category: 'Equipment', unit: 'Each', defaultCost: 580, isActive: true },
  { name: '80% AFUE 60k BTU Gas Furnace', category: 'Equipment', unit: 'Each', defaultCost: 680, isActive: true },
  { name: '80% AFUE 80k BTU Gas Furnace', category: 'Equipment', unit: 'Each', defaultCost: 800, isActive: true },
  { name: '80% AFUE 100k BTU Gas Furnace', category: 'Equipment', unit: 'Each', defaultCost: 950, isActive: true },
  { name: '96% AFUE 60k BTU Gas Furnace', category: 'Equipment', unit: 'Each', defaultCost: 950, isActive: true },
  { name: '96% AFUE 80k BTU Gas Furnace', category: 'Equipment', unit: 'Each', defaultCost: 1100, isActive: true },
  { name: '96% AFUE 100k BTU Gas Furnace', category: 'Equipment', unit: 'Each', defaultCost: 1250, isActive: true },
  { name: 'Electric Air Handler 10kW', category: 'Equipment', unit: 'Each', defaultCost: 620, isActive: true },
  { name: 'Electric Air Handler 15kW', category: 'Equipment', unit: 'Each', defaultCost: 720, isActive: true },
  { name: 'Electric Air Handler 20kW', category: 'Equipment', unit: 'Each', defaultCost: 850, isActive: true },
  { name: 'Package Unit 2 Ton AC Gas Heat', category: 'Equipment', unit: 'Each', defaultCost: 1400, isActive: true },
  { name: 'Package Unit 3 Ton AC Gas Heat', category: 'Equipment', unit: 'Each', defaultCost: 1650, isActive: true },
  { name: 'Package Unit 4 Ton AC Gas Heat', category: 'Equipment', unit: 'Each', defaultCost: 1900, isActive: true },
  { name: 'Package Unit 5 Ton AC Gas Heat', category: 'Equipment', unit: 'Each', defaultCost: 2200, isActive: true },
  { name: 'Package Unit 2 Ton Heat Pump', category: 'Equipment', unit: 'Each', defaultCost: 1550, isActive: true },
  { name: 'Package Unit 3 Ton Heat Pump', category: 'Equipment', unit: 'Each', defaultCost: 1800, isActive: true },
  { name: 'Package Unit 4 Ton Heat Pump', category: 'Equipment', unit: 'Each', defaultCost: 2100, isActive: true },
  { name: 'Package Unit 5 Ton Heat Pump', category: 'Equipment', unit: 'Each', defaultCost: 2400, isActive: true },
  { name: 'ERV Energy Recovery Ventilator', category: 'Equipment', unit: 'Each', defaultCost: 650, isActive: true },
  { name: 'HRV Heat Recovery Ventilator', category: 'Equipment', unit: 'Each', defaultCost: 600, isActive: true },
  { name: 'Whole House Dehumidifier 70 Pint', category: 'Equipment', unit: 'Each', defaultCost: 850, isActive: true },
  { name: 'Whole House Dehumidifier 90 Pint', category: 'Equipment', unit: 'Each', defaultCost: 1050, isActive: true },
  { name: 'UV Air Purifier Single Lamp', category: 'Equipment', unit: 'Each', defaultCost: 180, isActive: true },
  { name: 'UV Air Purifier Dual Lamp', category: 'Equipment', unit: 'Each', defaultCost: 280, isActive: true },
  { name: 'Electronic Air Cleaner', category: 'Equipment', unit: 'Each', defaultCost: 350, isActive: true },
  { name: 'HEPA Air Cleaner', category: 'Equipment', unit: 'Each', defaultCost: 420, isActive: true },
  { name: 'Whole House Humidifier Bypass', category: 'Equipment', unit: 'Each', defaultCost: 220, isActive: true },
  { name: 'Whole House Humidifier Power', category: 'Equipment', unit: 'Each', defaultCost: 380, isActive: true },

  // REFRIGERANT
  { name: 'R-410A 25 lb Cylinder', category: 'Refrigerant', unit: 'Each', defaultCost: 185, isActive: true },
  { name: 'R-410A 30 lb Cylinder', category: 'Refrigerant', unit: 'Each', defaultCost: 210, isActive: true },
  { name: 'R-22 30 lb Cylinder', category: 'Refrigerant', unit: 'Each', defaultCost: 450, isActive: true },
  { name: 'R-22 10 lb Cylinder', category: 'Refrigerant', unit: 'Each', defaultCost: 165, isActive: true },
  { name: 'R-32 11 lb Cylinder', category: 'Refrigerant', unit: 'Each', defaultCost: 95, isActive: true },
  { name: 'R-454B 25 lb Cylinder', category: 'Refrigerant', unit: 'Each', defaultCost: 225, isActive: true },
  { name: 'R-407C 25 lb Cylinder', category: 'Refrigerant', unit: 'Each', defaultCost: 195, isActive: true },
  { name: 'R-134A 30 lb Cylinder', category: 'Refrigerant', unit: 'Each', defaultCost: 120, isActive: true },
  { name: 'Refrigerant Recovery Cylinder 30 lb', category: 'Refrigerant', unit: 'Each', defaultCost: 45, isActive: true },
  { name: 'POE Oil 32 Viscosity 1 Quart', category: 'Refrigerant', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'POE Oil 68 Viscosity 1 Quart', category: 'Refrigerant', unit: 'Each', defaultCost: 20, isActive: true },
  { name: 'Mineral Oil 1 Quart', category: 'Refrigerant', unit: 'Each', defaultCost: 14, isActive: true },
  { name: 'Vacuum Pump Oil 1 Quart', category: 'Refrigerant', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Nitrogen Cylinder Exchange & Braze Rods', category: 'Refrigerant', unit: 'Each', defaultCost: 75, isActive: true },
  { name: 'Nitrogen Regulator', category: 'Refrigerant', unit: 'Each', defaultCost: 65, isActive: true },

  // COPPER & FITTINGS
  { name: '1/4" ACR Copper Tubing', category: 'Copper & Fittings', unit: 'Foot', defaultCost: 1.80, isActive: true },
  { name: '3/8" ACR Copper Tubing', category: 'Copper & Fittings', unit: 'Foot', defaultCost: 2.80, isActive: true },
  { name: '1/2" ACR Copper Tubing', category: 'Copper & Fittings', unit: 'Foot', defaultCost: 3.50, isActive: true },
  { name: '5/8" ACR Copper Tubing', category: 'Copper & Fittings', unit: 'Foot', defaultCost: 4.50, isActive: true },
  { name: '3/4" ACR Copper Tubing', category: 'Copper & Fittings', unit: 'Foot', defaultCost: 5.50, isActive: true },
  { name: '7/8" ACR Copper Tubing', category: 'Copper & Fittings', unit: 'Foot', defaultCost: 7.00, isActive: true },
  { name: '1-1/8" ACR Copper Tubing', category: 'Copper & Fittings', unit: 'Foot', defaultCost: 9.00, isActive: true },
  { name: '1-3/8" ACR Copper Tubing', category: 'Copper & Fittings', unit: 'Foot', defaultCost: 13.00, isActive: true },
  { name: 'Pre-Charged Line Set 3/8 x 3/4 25ft', category: 'Copper & Fittings', unit: 'Each', defaultCost: 145, isActive: true },
  { name: 'Pre-Charged Line Set 3/8 x 3/4 50ft', category: 'Copper & Fittings', unit: 'Each', defaultCost: 220, isActive: true },
  { name: 'Pre-Charged Line Set 1/2 x 7/8 25ft', category: 'Copper & Fittings', unit: 'Each', defaultCost: 185, isActive: true },
  { name: 'Pre-Charged Line Set 1/2 x 7/8 50ft', category: 'Copper & Fittings', unit: 'Each', defaultCost: 275, isActive: true },
  { name: 'Copper 90 Degree Elbow 3/8"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 2.50, isActive: true },
  { name: 'Copper 90 Degree Elbow 1/2"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 3.00, isActive: true },
  { name: 'Copper 90 Degree Elbow 5/8"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 3.75, isActive: true },
  { name: 'Copper 90 Degree Elbow 3/4"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 4.50, isActive: true },
  { name: 'Copper 90 Degree Elbow 7/8"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 6.00, isActive: true },
  { name: 'Copper 45 Degree Elbow 3/8"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 2.25, isActive: true },
  { name: 'Copper 45 Degree Elbow 1/2"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 2.75, isActive: true },
  { name: 'Copper Tee 3/8"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 3.50, isActive: true },
  { name: 'Copper Tee 1/2"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 4.00, isActive: true },
  { name: 'Copper Coupling 3/8"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 1.75, isActive: true },
  { name: 'Copper Coupling 1/2"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 2.00, isActive: true },
  { name: 'Copper Cap 3/8"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 1.50, isActive: true },
  { name: 'Copper Cap 1/2"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 1.75, isActive: true },
  { name: 'Copper Reducer 1/2 x 3/8"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 2.50, isActive: true },
  { name: 'Copper Reducer 5/8 x 1/2"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 3.00, isActive: true },
  { name: 'Copper Reducer 7/8 x 3/4"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 4.50, isActive: true },
  { name: 'Flare Nut 1/4"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 2.00, isActive: true },
  { name: 'Flare Nut 3/8"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 2.50, isActive: true },
  { name: 'Flare Nut 1/2"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 3.00, isActive: true },
  { name: 'Flare Nut 5/8"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 3.75, isActive: true },
  { name: 'Flare Nut 3/4"', category: 'Copper & Fittings', unit: 'Each', defaultCost: 4.50, isActive: true },
  { name: 'Copper Line Set Insulation 1/2" x 6ft', category: 'Copper & Fittings', unit: 'Each', defaultCost: 4.00, isActive: true },
  { name: 'Copper Line Set Insulation 3/4" x 6ft', category: 'Copper & Fittings', unit: 'Each', defaultCost: 5.00, isActive: true },
  { name: 'Copper Line Set Insulation 7/8" x 6ft', category: 'Copper & Fittings', unit: 'Each', defaultCost: 6.00, isActive: true },
  { name: 'Copper Line Set Insulation 1-1/8" x 6ft', category: 'Copper & Fittings', unit: 'Each', defaultCost: 7.50, isActive: true },
  { name: 'Line Set Cover Kit White (small)', category: 'Copper & Fittings', unit: 'Each', defaultCost: 38, isActive: true },
  { name: 'Line Set Cover Kit White (large)', category: 'Copper & Fittings', unit: 'Each', defaultCost: 55, isActive: true },
  { name: 'Schrader Valve Core', category: 'Copper & Fittings', unit: 'Each', defaultCost: 2.00, isActive: true },
  { name: 'Access Valve 1/4" Flare', category: 'Copper & Fittings', unit: 'Each', defaultCost: 8.00, isActive: true },
  { name: 'Access Valve 3/8" Flare', category: 'Copper & Fittings', unit: 'Each', defaultCost: 9.00, isActive: true },
  { name: 'Silver Solder 15% Stick', category: 'Copper & Fittings', unit: 'Each', defaultCost: 4.50, isActive: true },
  { name: 'Emery Cloth / Sandpaper Roll', category: 'Copper & Fittings', unit: 'Each', defaultCost: 3.00, isActive: true },

  // ELECTRICAL
  { name: '30A 240V Non-Fused Disconnect', category: 'Electrical', unit: 'Each', defaultCost: 18, isActive: true },
  { name: '60A 240V Non-Fused Disconnect', category: 'Electrical', unit: 'Each', defaultCost: 28, isActive: true },
  { name: '100A 240V Non-Fused Disconnect', category: 'Electrical', unit: 'Each', defaultCost: 45, isActive: true },
  { name: '30A 240V Fused Disconnect', category: 'Electrical', unit: 'Each', defaultCost: 32, isActive: true },
  { name: '60A 240V Fused Disconnect', category: 'Electrical', unit: 'Each', defaultCost: 48, isActive: true },
  { name: '30A 240V Cartridge Fuses (pair)', category: 'Electrical', unit: 'Each', defaultCost: 8, isActive: true },
  { name: '60A 240V Cartridge Fuses (pair)', category: 'Electrical', unit: 'Each', defaultCost: 12, isActive: true },
  { name: '6ft 10/3 Liquid-Tight Electrical Whip', category: 'Electrical', unit: 'Each', defaultCost: 18, isActive: true },
  { name: '6ft 8/3 Liquid-Tight Electrical Whip', category: 'Electrical', unit: 'Each', defaultCost: 24, isActive: true },
  { name: '10/2 Romex Wire', category: 'Electrical', unit: 'Foot', defaultCost: 1.80, isActive: true },
  { name: '8/2 Romex Wire', category: 'Electrical', unit: 'Foot', defaultCost: 2.40, isActive: true },
  { name: '6/2 Romex Wire', category: 'Electrical', unit: 'Foot', defaultCost: 3.20, isActive: true },
  { name: '10/3 Romex Wire', category: 'Electrical', unit: 'Foot', defaultCost: 2.20, isActive: true },
  { name: '1/2" Liquid-Tight Conduit', category: 'Electrical', unit: 'Foot', defaultCost: 1.20, isActive: true },
  { name: '3/4" Liquid-Tight Conduit', category: 'Electrical', unit: 'Foot', defaultCost: 1.60, isActive: true },
  { name: '1/2" PVC Electrical Conduit', category: 'Electrical', unit: 'Foot', defaultCost: 0.75, isActive: true },
  { name: '3/4" PVC Electrical Conduit', category: 'Electrical', unit: 'Foot', defaultCost: 0.95, isActive: true },
  { name: 'Contactor 1 Pole 24V 30A', category: 'Electrical', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'Contactor 2 Pole 24V 30A', category: 'Electrical', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Contactor 2 Pole 24V 40A', category: 'Electrical', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Contactor 2 Pole 24V 50A', category: 'Electrical', unit: 'Each', defaultCost: 34, isActive: true },
  { name: 'Run Capacitor 25/5 MFD 370V', category: 'Electrical', unit: 'Each', defaultCost: 10, isActive: true },
  { name: 'Run Capacitor 35/5 MFD 370V', category: 'Electrical', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Run Capacitor 45/5 MFD 370V', category: 'Electrical', unit: 'Each', defaultCost: 14, isActive: true },
  { name: 'Run Capacitor 55/5 MFD 370V', category: 'Electrical', unit: 'Each', defaultCost: 16, isActive: true },
  { name: 'Run Capacitor 35/5 MFD 440V', category: 'Electrical', unit: 'Each', defaultCost: 14, isActive: true },
  { name: 'Run Capacitor 45/5 MFD 440V', category: 'Electrical', unit: 'Each', defaultCost: 16, isActive: true },
  { name: 'Start Capacitor 88-108 MFD', category: 'Electrical', unit: 'Each', defaultCost: 16, isActive: true },
  { name: 'Start Capacitor 108-130 MFD', category: 'Electrical', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'Start Capacitor 161-193 MFD', category: 'Electrical', unit: 'Each', defaultCost: 20, isActive: true },
  { name: 'Hard Start Kit (PTCR)', category: 'Electrical', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Condenser Fan Motor 1/6 HP', category: 'Electrical', unit: 'Each', defaultCost: 75, isActive: true },
  { name: 'Condenser Fan Motor 1/4 HP', category: 'Electrical', unit: 'Each', defaultCost: 85, isActive: true },
  { name: 'Condenser Fan Motor 1/3 HP', category: 'Electrical', unit: 'Each', defaultCost: 95, isActive: true },
  { name: 'Condenser Fan Motor 1/2 HP', category: 'Electrical', unit: 'Each', defaultCost: 110, isActive: true },
  { name: 'Condenser Fan Blade 20"', category: 'Electrical', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Condenser Fan Blade 24"', category: 'Electrical', unit: 'Each', defaultCost: 32, isActive: true },
  { name: 'Condenser Fan Blade 26"', category: 'Electrical', unit: 'Each', defaultCost: 36, isActive: true },
  { name: 'Blower Motor 1/3 HP PSC', category: 'Electrical', unit: 'Each', defaultCost: 95, isActive: true },
  { name: 'Blower Motor 1/2 HP PSC', category: 'Electrical', unit: 'Each', defaultCost: 110, isActive: true },
  { name: 'Blower Motor 3/4 HP PSC', category: 'Electrical', unit: 'Each', defaultCost: 130, isActive: true },
  { name: 'ECM Blower Motor 1/2 HP', category: 'Electrical', unit: 'Each', defaultCost: 280, isActive: true },
  { name: 'ECM Blower Motor 3/4 HP', category: 'Electrical', unit: 'Each', defaultCost: 320, isActive: true },
  { name: 'ECM Blower Motor Control Module', category: 'Electrical', unit: 'Each', defaultCost: 180, isActive: true },
  { name: '24V Transformer 40VA', category: 'Electrical', unit: 'Each', defaultCost: 18, isActive: true },
  { name: '24V Transformer 75VA', category: 'Electrical', unit: 'Each', defaultCost: 24, isActive: true },
  { name: 'Low Voltage Wire 18/2 per foot', category: 'Electrical', unit: 'Foot', defaultCost: 0.25, isActive: true },
  { name: 'Low Voltage Wire 18/5 per foot', category: 'Electrical', unit: 'Foot', defaultCost: 0.35, isActive: true },
  { name: 'Low Voltage Wire 18/8 per foot', category: 'Electrical', unit: 'Foot', defaultCost: 0.45, isActive: true },
  { name: 'Wire Connector Nuts Box/100', category: 'Electrical', unit: 'Box', defaultCost: 12, isActive: true },
  { name: 'Electrical Tape Roll', category: 'Electrical', unit: 'Each', defaultCost: 3, isActive: true },
  { name: 'Disconnect Pull Out Block 30A', category: 'Electrical', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'Surge Protector HVAC Unit', category: 'Electrical', unit: 'Each', defaultCost: 55, isActive: true },
  { name: 'Time Delay Relay', category: 'Electrical', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Crankcase Heater 40W', category: 'Electrical', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'Defrost Control Board', category: 'Electrical', unit: 'Each', defaultCost: 85, isActive: true },
  { name: 'Control Board Universal', category: 'Electrical', unit: 'Each', defaultCost: 120, isActive: true },

  // DUCTWORK
  { name: '4" R-6 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 38, isActive: true },
  { name: '5" R-6 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 42, isActive: true },
  { name: '6" R-6 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 48, isActive: true },
  { name: '7" R-6 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 55, isActive: true },
  { name: '8" R-6 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 62, isActive: true },
  { name: '9" R-6 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 72, isActive: true },
  { name: '10" R-6 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 80, isActive: true },
  { name: '12" R-6 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 95, isActive: true },
  { name: '14" R-6 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 115, isActive: true },
  { name: '4" R-8 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 48, isActive: true },
  { name: '6" R-8 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 60, isActive: true },
  { name: '8" R-8 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 78, isActive: true },
  { name: '10" R-8 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 98, isActive: true },
  { name: '12" R-8 Flexible Duct 25ft', category: 'Ductwork', unit: 'Each', defaultCost: 120, isActive: true },
  { name: 'Sheet Metal Duct 4" Round x 5ft', category: 'Ductwork', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Sheet Metal Duct 6" Round x 5ft', category: 'Ductwork', unit: 'Each', defaultCost: 16, isActive: true },
  { name: 'Sheet Metal Duct 8" Round x 5ft', category: 'Ductwork', unit: 'Each', defaultCost: 20, isActive: true },
  { name: 'Sheet Metal Duct 10" Round x 5ft', category: 'Ductwork', unit: 'Each', defaultCost: 26, isActive: true },
  { name: 'Sheet Metal Duct 12" Round x 5ft', category: 'Ductwork', unit: 'Each', defaultCost: 32, isActive: true },
  { name: 'Sheet Metal Duct 6x4 Rectangular x 4ft', category: 'Ductwork', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'Sheet Metal Duct 8x4 Rectangular x 4ft', category: 'Ductwork', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Sheet Metal Duct 10x6 Rectangular x 4ft', category: 'Ductwork', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Sheet Metal Duct 12x6 Rectangular x 4ft', category: 'Ductwork', unit: 'Each', defaultCost: 34, isActive: true },
  { name: 'Sheet Metal Duct 14x8 Rectangular x 4ft', category: 'Ductwork', unit: 'Each', defaultCost: 42, isActive: true },
  { name: 'Starting Collar 4"', category: 'Ductwork', unit: 'Each', defaultCost: 6, isActive: true },
  { name: 'Starting Collar 5"', category: 'Ductwork', unit: 'Each', defaultCost: 7, isActive: true },
  { name: 'Starting Collar 6"', category: 'Ductwork', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'Starting Collar 7"', category: 'Ductwork', unit: 'Each', defaultCost: 9, isActive: true },
  { name: 'Starting Collar 8"', category: 'Ductwork', unit: 'Each', defaultCost: 10, isActive: true },
  { name: 'Starting Collar 10"', category: 'Ductwork', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Starting Collar 12"', category: 'Ductwork', unit: 'Each', defaultCost: 15, isActive: true },
  { name: 'Duct Connector Zip Collar 6"', category: 'Ductwork', unit: 'Each', defaultCost: 6, isActive: true },
  { name: 'Duct Connector Zip Collar 8"', category: 'Ductwork', unit: 'Each', defaultCost: 7, isActive: true },
  { name: 'Duct Connector Zip Collar 10"', category: 'Ductwork', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'Duct Connector Zip Collar 12"', category: 'Ductwork', unit: 'Each', defaultCost: 10, isActive: true },
  { name: 'Flexible Duct Elbow 6"', category: 'Ductwork', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'Flexible Duct Elbow 8"', category: 'Ductwork', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Flexible Duct Elbow 10"', category: 'Ductwork', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Sheet Metal 90 Elbow 6"', category: 'Ductwork', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Sheet Metal 90 Elbow 8"', category: 'Ductwork', unit: 'Each', defaultCost: 15, isActive: true },
  { name: 'Sheet Metal 90 Elbow 10"', category: 'Ductwork', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'Sheet Metal Wye 6x6x6', category: 'Ductwork', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Sheet Metal Wye 8x6x6', category: 'Ductwork', unit: 'Each', defaultCost: 26, isActive: true },
  { name: 'Sheet Metal Wye 10x8x6', category: 'Ductwork', unit: 'Each', defaultCost: 32, isActive: true },
  { name: 'Supply Plenum Pre-Fab Small', category: 'Ductwork', unit: 'Each', defaultCost: 75, isActive: true },
  { name: 'Supply Plenum Pre-Fab Medium', category: 'Ductwork', unit: 'Each', defaultCost: 95, isActive: true },
  { name: 'Supply Plenum Pre-Fab Large', category: 'Ductwork', unit: 'Each', defaultCost: 120, isActive: true },
  { name: 'Return Air Plenum Small', category: 'Ductwork', unit: 'Each', defaultCost: 65, isActive: true },
  { name: 'Return Air Plenum Large', category: 'Ductwork', unit: 'Each', defaultCost: 85, isActive: true },
  { name: 'Custom Sheet Metal Supply Plenum', category: 'Ductwork', unit: 'Each', defaultCost: 125, isActive: true },
  { name: 'Duct Board 1" 4x8 Sheet', category: 'Ductwork', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Duct Board 1.5" 4x8 Sheet', category: 'Ductwork', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Duct Board 2" 4x8 Sheet', category: 'Ductwork', unit: 'Each', defaultCost: 34, isActive: true },
  { name: 'Mastic Sealant 1 Gallon', category: 'Ductwork', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Silver Foil Scrim Duct Tape UL 181', category: 'Ductwork', unit: 'Each', defaultCost: 16, isActive: true },
  { name: 'Foil HVAC Tape Roll', category: 'Ductwork', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Sheet Metal Screws #8 Box/100', category: 'Ductwork', unit: 'Box', defaultCost: 12, isActive: true },
  { name: 'Sheet Metal Screws #10 Box/100', category: 'Ductwork', unit: 'Box', defaultCost: 14, isActive: true },
  { name: 'Self-Drilling Screws Box/100', category: 'Ductwork', unit: 'Box', defaultCost: 14, isActive: true },
  { name: '36" Heavy Duty Nylon Duct Ties', category: 'Ductwork', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Register Box 4x8x4', category: 'Ductwork', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'Register Box 6x8x4', category: 'Ductwork', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Register Box 8x4x4', category: 'Ductwork', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Register Box 10x6x6', category: 'Ductwork', unit: 'Each', defaultCost: 34, isActive: true },
  { name: 'Register Box 12x6x7', category: 'Ductwork', unit: 'Each', defaultCost: 38, isActive: true },
  { name: 'Register Box 12x12x9', category: 'Ductwork', unit: 'Each', defaultCost: 44, isActive: true },
  { name: 'Transition Box 14x8 to 12x6', category: 'Ductwork', unit: 'Each', defaultCost: 32, isActive: true },
  { name: '20x20 Filter Return Grille', category: 'Ductwork', unit: 'Each', defaultCost: 45, isActive: true },
  { name: '20x25 Filter Return Grille', category: 'Ductwork', unit: 'Each', defaultCost: 52, isActive: true },
  { name: '25x25 Filter Return Grille', category: 'Ductwork', unit: 'Each', defaultCost: 58, isActive: true },
  { name: 'Supply Register 4x10 White', category: 'Ductwork', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'Supply Register 4x12 White', category: 'Ductwork', unit: 'Each', defaultCost: 9, isActive: true },
  { name: 'Supply Register 6x10 White', category: 'Ductwork', unit: 'Each', defaultCost: 10, isActive: true },
  { name: 'Supply Register 6x12 White', category: 'Ductwork', unit: 'Each', defaultCost: 11, isActive: true },
  { name: 'Supply Register 8x12 White', category: 'Ductwork', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Supply Register 10x12 White', category: 'Ductwork', unit: 'Each', defaultCost: 14, isActive: true },
  { name: 'Return Grille 14x14 White', category: 'Ductwork', unit: 'Each', defaultCost: 14, isActive: true },
  { name: 'Return Grille 16x20 White', category: 'Ductwork', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'Return Grille 20x20 White', category: 'Ductwork', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Return Grille 20x25 White', category: 'Ductwork', unit: 'Each', defaultCost: 26, isActive: true },
  { name: 'Barometric Damper 6"', category: 'Ductwork', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Barometric Damper 8"', category: 'Ductwork', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Manual Volume Damper 6"', category: 'Ductwork', unit: 'Each', defaultCost: 14, isActive: true },
  { name: 'Manual Volume Damper 8"', category: 'Ductwork', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'Manual Volume Damper 10"', category: 'Ductwork', unit: 'Each', defaultCost: 22, isActive: true },

  // INSULATION
  { name: 'Duct Wrap Insulation R-6 1.5"x48"x25ft', category: 'Insulation', unit: 'Each', defaultCost: 55, isActive: true },
  { name: 'Duct Wrap Insulation R-8 2"x48"x25ft', category: 'Insulation', unit: 'Each', defaultCost: 72, isActive: true },
  { name: 'Duct Wrap Insulation R-11 3"x48"x25ft', category: 'Insulation', unit: 'Each', defaultCost: 90, isActive: true },
  { name: 'Pipe Insulation 1/2" x 6ft', category: 'Insulation', unit: 'Each', defaultCost: 3.50, isActive: true },
  { name: 'Pipe Insulation 3/4" x 6ft', category: 'Insulation', unit: 'Each', defaultCost: 4.00, isActive: true },
  { name: 'Pipe Insulation 7/8" x 6ft', category: 'Insulation', unit: 'Each', defaultCost: 4.50, isActive: true },
  { name: 'Pipe Insulation 1-1/8" x 6ft', category: 'Insulation', unit: 'Each', defaultCost: 5.50, isActive: true },
  { name: 'Pipe Insulation 1-3/8" x 6ft', category: 'Insulation', unit: 'Each', defaultCost: 6.50, isActive: true },
  { name: 'Armaflex Sheet 1/2" 48"x36"', category: 'Insulation', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Armaflex Sheet 1" 48"x36"', category: 'Insulation', unit: 'Each', defaultCost: 42, isActive: true },
  { name: 'Spray Foam Insulation Can', category: 'Insulation', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'Fiberglass Batts R-13 per bag', category: 'Insulation', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Fiberglass Batts R-19 per bag', category: 'Insulation', unit: 'Each', defaultCost: 36, isActive: true },
  { name: 'Reflective Radiant Barrier Roll', category: 'Insulation', unit: 'Each', defaultCost: 65, isActive: true },

  // CONTROLS & THERMOSTATS
  { name: 'Non-Programmable Thermostat', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 25, isActive: true },
  { name: '7-Day Programmable Thermostat', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 45, isActive: true },
  { name: 'Smart WiFi Thermostat (Ecobee-type)', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 185, isActive: true },
  { name: 'Smart WiFi Thermostat (Nest-type)', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 200, isActive: true },
  { name: 'Smart WiFi Thermostat (Honeywell T6 Pro)', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 65, isActive: true },
  { name: 'Smart WiFi Thermostat (Emerson Sensi)', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 80, isActive: true },
  { name: 'Thermostat Sub-Base', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Thermostat Wire 18/5 50ft Spool', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 32, isActive: true },
  { name: 'Thermostat Wire 18/8 50ft Spool', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 45, isActive: true },
  { name: 'Thermostat Wire 18/10 50ft Spool', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 58, isActive: true },
  { name: 'Zone Control Board 2 Zone', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 120, isActive: true },
  { name: 'Zone Control Board 4 Zone', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 180, isActive: true },
  { name: 'Zone Control Board 6 Zone', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 240, isActive: true },
  { name: 'Zone Damper 6" Round Motorized', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 55, isActive: true },
  { name: 'Zone Damper 8" Round Motorized', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 65, isActive: true },
  { name: 'Zone Damper 10" Round Motorized', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 75, isActive: true },
  { name: 'Zone Damper 12" Round Motorized', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 90, isActive: true },
  { name: 'Bypass Damper 8"', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 65, isActive: true },
  { name: 'Bypass Damper 10"', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 75, isActive: true },
  { name: 'High Pressure Switch', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Low Pressure Switch', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Dual Pressure Switch', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 48, isActive: true },
  { name: 'Freeze Stat', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Duct Smoke Detector', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 85, isActive: true },
  { name: 'CO Detector', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 45, isActive: true },
  { name: 'Economizer Controller', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 185, isActive: true },
  { name: 'Compressor Saver (Hard Start)', category: 'Controls & Thermostats', unit: 'Each', defaultCost: 45, isActive: true },

  // FILTERS
  { name: '14x20x1 MERV 8 Filter', category: 'Filters', unit: 'Each', defaultCost: 7, isActive: true },
  { name: '14x25x1 MERV 8 Filter', category: 'Filters', unit: 'Each', defaultCost: 8, isActive: true },
  { name: '16x20x1 MERV 8 Filter', category: 'Filters', unit: 'Each', defaultCost: 8, isActive: true },
  { name: '16x25x1 MERV 8 Filter', category: 'Filters', unit: 'Each', defaultCost: 9, isActive: true },
  { name: '20x20x1 MERV 8 Filter', category: 'Filters', unit: 'Each', defaultCost: 9, isActive: true },
  { name: '20x25x1 MERV 8 Filter', category: 'Filters', unit: 'Each', defaultCost: 10, isActive: true },
  { name: '24x24x1 MERV 8 Filter', category: 'Filters', unit: 'Each', defaultCost: 11, isActive: true },
  { name: '16x20x1 MERV 11 Filter', category: 'Filters', unit: 'Each', defaultCost: 12, isActive: true },
  { name: '16x25x1 MERV 11 Filter', category: 'Filters', unit: 'Each', defaultCost: 13, isActive: true },
  { name: '20x20x1 MERV 11 Filter', category: 'Filters', unit: 'Each', defaultCost: 13, isActive: true },
  { name: '20x25x1 MERV 11 Filter', category: 'Filters', unit: 'Each', defaultCost: 14, isActive: true },
  { name: '16x25x4 MERV 11 Media Filter', category: 'Filters', unit: 'Each', defaultCost: 28, isActive: true },
  { name: '20x20x4 MERV 11 Media Filter', category: 'Filters', unit: 'Each', defaultCost: 30, isActive: true },
  { name: '20x25x4 MERV 11 Media Filter', category: 'Filters', unit: 'Each', defaultCost: 34, isActive: true },
  { name: '20x25x5 MERV 11 Media Filter', category: 'Filters', unit: 'Each', defaultCost: 38, isActive: true },
  { name: '16x25x5 MERV 13 Media Filter', category: 'Filters', unit: 'Each', defaultCost: 42, isActive: true },
  { name: '20x25x5 MERV 13 Media Filter', category: 'Filters', unit: 'Each', defaultCost: 48, isActive: true },
  { name: '16x20x1 MERV 13 Filter', category: 'Filters', unit: 'Each', defaultCost: 16, isActive: true },
  { name: '20x25x1 MERV 13 Filter', category: 'Filters', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'HEPA Filter Replacement', category: 'Filters', unit: 'Each', defaultCost: 65, isActive: true },
  { name: 'Electronic Air Cleaner Cell', category: 'Filters', unit: 'Each', defaultCost: 85, isActive: true },
  { name: 'UV Lamp Replacement 9"', category: 'Filters', unit: 'Each', defaultCost: 45, isActive: true },
  { name: 'UV Lamp Replacement 14"', category: 'Filters', unit: 'Each', defaultCost: 55, isActive: true },

  // DRAIN & PVC
  { name: '3/4" PVC Schedule 40 Pipe 10ft', category: 'Drain & PVC', unit: 'Each', defaultCost: 8, isActive: true },
  { name: '1" PVC Schedule 40 Pipe 10ft', category: 'Drain & PVC', unit: 'Each', defaultCost: 10, isActive: true },
  { name: '1-1/4" PVC Schedule 40 Pipe 10ft', category: 'Drain & PVC', unit: 'Each', defaultCost: 13, isActive: true },
  { name: '1-1/2" PVC Schedule 40 Pipe 10ft', category: 'Drain & PVC', unit: 'Each', defaultCost: 16, isActive: true },
  { name: '2" PVC Schedule 40 Pipe 10ft', category: 'Drain & PVC', unit: 'Each', defaultCost: 20, isActive: true },
  { name: '3/4" PVC 90 Elbow', category: 'Drain & PVC', unit: 'Each', defaultCost: 0.75, isActive: true },
  { name: '1" PVC 90 Elbow', category: 'Drain & PVC', unit: 'Each', defaultCost: 0.90, isActive: true },
  { name: '1-1/2" PVC 90 Elbow', category: 'Drain & PVC', unit: 'Each', defaultCost: 1.25, isActive: true },
  { name: '2" PVC 90 Elbow', category: 'Drain & PVC', unit: 'Each', defaultCost: 1.75, isActive: true },
  { name: '3/4" PVC 45 Elbow', category: 'Drain & PVC', unit: 'Each', defaultCost: 0.75, isActive: true },
  { name: '1" PVC 45 Elbow', category: 'Drain & PVC', unit: 'Each', defaultCost: 0.90, isActive: true },
  { name: '3/4" PVC Tee', category: 'Drain & PVC', unit: 'Each', defaultCost: 0.85, isActive: true },
  { name: '1" PVC Tee', category: 'Drain & PVC', unit: 'Each', defaultCost: 1.00, isActive: true },
  { name: '3/4" PVC Coupling', category: 'Drain & PVC', unit: 'Each', defaultCost: 0.60, isActive: true },
  { name: '1" PVC Coupling', category: 'Drain & PVC', unit: 'Each', defaultCost: 0.75, isActive: true },
  { name: '3/4" PVC Cap', category: 'Drain & PVC', unit: 'Each', defaultCost: 0.50, isActive: true },
  { name: '1" PVC Cap', category: 'Drain & PVC', unit: 'Each', defaultCost: 0.65, isActive: true },
  { name: '3/4" PVC Union', category: 'Drain & PVC', unit: 'Each', defaultCost: 2.50, isActive: true },
  { name: '1" PVC Union', category: 'Drain & PVC', unit: 'Each', defaultCost: 3.00, isActive: true },
  { name: 'PVC Cement Regular Clear Small', category: 'Drain & PVC', unit: 'Each', defaultCost: 6, isActive: true },
  { name: 'PVC Primer Purple Small', category: 'Drain & PVC', unit: 'Each', defaultCost: 5, isActive: true },
  { name: 'PVC Cement Medium Blue', category: 'Drain & PVC', unit: 'Each', defaultCost: 10, isActive: true },
  { name: 'Condensate Drain Pan Metal 14x14', category: 'Drain & PVC', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Condensate Drain Pan Metal 16x16', category: 'Drain & PVC', unit: 'Each', defaultCost: 32, isActive: true },
  { name: 'Condensate Drain Pan Plastic 20x20', category: 'Drain & PVC', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Secondary Condensate Pan 30x30', category: 'Drain & PVC', unit: 'Each', defaultCost: 38, isActive: true },
  { name: 'Condensate Pump 115V', category: 'Drain & PVC', unit: 'Each', defaultCost: 65, isActive: true },
  { name: 'Condensate Pump with Safety Switch', category: 'Drain & PVC', unit: 'Each', defaultCost: 85, isActive: true },
  { name: 'Float Switch SS2', category: 'Drain & PVC', unit: 'Each', defaultCost: 38, isActive: true },
  { name: 'Float Switch Horizontal', category: 'Drain & PVC', unit: 'Each', defaultCost: 18, isActive: true },
  { name: 'Wet Switch Water Detector', category: 'Drain & PVC', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Drain Line Cleaning Tabs', category: 'Drain & PVC', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'Condensate Trap 3/4"', category: 'Drain & PVC', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Air Vent Cap 3/4"', category: 'Drain & PVC', unit: 'Each', defaultCost: 4, isActive: true },

  // HARDWARE & FASTENERS
  { name: 'Concrete Pad 30x30x3', category: 'Hardware & Fasteners', unit: 'Each', defaultCost: 42, isActive: true },
  { name: 'Concrete Pad 32x32x3', category: 'Hardware & Fasteners', unit: 'Each', defaultCost: 48, isActive: true },
  { name: 'Concrete Pad 36x36x3', category: 'Hardware & Fasteners', unit: 'Each', defaultCost: 55, isActive: true },
  { name: 'Plastic Pad 30x30', category: 'Hardware & Fasteners', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Plastic Pad 36x36', category: 'Hardware & Fasteners', unit: 'Each', defaultCost: 35, isActive: true },
  { name: 'Equipment Pad Riser Set of 4', category: 'Hardware & Fasteners', unit: 'Set', defaultCost: 18, isActive: true },
  { name: 'Vibration Isolator Pads Set of 4', category: 'Hardware & Fasteners', unit: 'Set', defaultCost: 22, isActive: true },
  { name: 'Anti-Vibration Rubber Feet Set of 4', category: 'Hardware & Fasteners', unit: 'Set', defaultCost: 16, isActive: true },
  { name: 'Hurricane Straps / Locking Caps Set', category: 'Hardware & Fasteners', unit: 'Set', defaultCost: 28, isActive: true },
  { name: 'All-Thread Rod 3/8" x 10ft', category: 'Hardware & Fasteners', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'All-Thread Rod 1/2" x 10ft', category: 'Hardware & Fasteners', unit: 'Each', defaultCost: 16, isActive: true },
  { name: 'Strut Channel 1-5/8" x 10ft', category: 'Hardware & Fasteners', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'Strut Clamp 3/4" Box/10', category: 'Hardware & Fasteners', unit: 'Box', defaultCost: 18, isActive: true },
  { name: 'Strut Clamp 1" Box/10', category: 'Hardware & Fasteners', unit: 'Box', defaultCost: 20, isActive: true },
  { name: 'Hanger Strap 1" x 10ft', category: 'Hardware & Fasteners', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'J-Hook 1/2" Box/25', category: 'Hardware & Fasteners', unit: 'Box', defaultCost: 14, isActive: true },
  { name: 'J-Hook 3/4" Box/25', category: 'Hardware & Fasteners', unit: 'Box', defaultCost: 16, isActive: true },
  { name: 'Anchor Bolts 3/8" Box/25', category: 'Hardware & Fasteners', unit: 'Box', defaultCost: 14, isActive: true },
  { name: 'Tapcon Screws 3/16" Box/25', category: 'Hardware & Fasteners', unit: 'Box', defaultCost: 12, isActive: true },
  { name: 'Lag Screws 5/16" Box/25', category: 'Hardware & Fasteners', unit: 'Box', defaultCost: 10, isActive: true },
  { name: 'UV-Resistant Zip Ties 8" Bag/100', category: 'Hardware & Fasteners', unit: 'Bag', defaultCost: 8, isActive: true },
  { name: 'UV-Resistant Zip Ties 12" Bag/100', category: 'Hardware & Fasteners', unit: 'Bag', defaultCost: 10, isActive: true },
  { name: 'Foam Weatherstrip Tape Roll', category: 'Hardware & Fasteners', unit: 'Each', defaultCost: 6, isActive: true },
  { name: 'Pipe Hanger 3/4" Box/10', category: 'Hardware & Fasteners', unit: 'Box', defaultCost: 10, isActive: true },
  { name: 'Pipe Hanger 1" Box/10', category: 'Hardware & Fasteners', unit: 'Box', defaultCost: 12, isActive: true },
  { name: 'Split Ring Hanger 3/4" Box/10', category: 'Hardware & Fasteners', unit: 'Box', defaultCost: 14, isActive: true },
  { name: 'Teflon Tape Roll', category: 'Hardware & Fasteners', unit: 'Each', defaultCost: 2.50, isActive: true },

  // TOOLS & CONSUMABLES
  { name: 'Flux Paste 4oz', category: 'Tools & Consumables', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'Silver Solder 45% Stick', category: 'Tools & Consumables', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'MAP Gas Cylinder', category: 'Tools & Consumables', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Propane Cylinder', category: 'Tools & Consumables', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'Refrigerant Leak Detector Spray', category: 'Tools & Consumables', unit: 'Each', defaultCost: 10, isActive: true },
  { name: 'Coil Cleaner Foaming 18oz', category: 'Tools & Consumables', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Coil Cleaner No-Rinse 18oz', category: 'Tools & Consumables', unit: 'Each', defaultCost: 14, isActive: true },
  { name: 'Nu-Brite Coil Cleaner Gallon', category: 'Tools & Consumables', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Condensate Pan Cleaner Tabs', category: 'Tools & Consumables', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'Caulk Tube White', category: 'Tools & Consumables', unit: 'Each', defaultCost: 4, isActive: true },
  { name: 'Silicone Sealant Tube', category: 'Tools & Consumables', unit: 'Each', defaultCost: 6, isActive: true },
  { name: 'Putty Pad Fire Stop', category: 'Tools & Consumables', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Cable Ties Bag/100', category: 'Tools & Consumables', unit: 'Bag', defaultCost: 6, isActive: true },
  { name: 'Blue Shop Towels Roll', category: 'Tools & Consumables', unit: 'Each', defaultCost: 5, isActive: true },
  { name: 'Nitrile Gloves Box/100', category: 'Tools & Consumables', unit: 'Box', defaultCost: 14, isActive: true },
  { name: 'Duct Knife', category: 'Tools & Consumables', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'Utility Knife Blades Box/10', category: 'Tools & Consumables', unit: 'Box', defaultCost: 8, isActive: true },

  // SAFETY
  { name: 'Safety Glasses Clear', category: 'Safety', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'Safety Glasses Tinted', category: 'Safety', unit: 'Each', defaultCost: 8, isActive: true },
  { name: 'Work Gloves Leather Pair', category: 'Safety', unit: 'Each', defaultCost: 14, isActive: true },
  { name: 'R-410A Cryo Gloves Pair', category: 'Safety', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Knee Pads', category: 'Safety', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'N95 Dust Masks Box/10', category: 'Safety', unit: 'Box', defaultCost: 18, isActive: true },
  { name: 'Half-Face Respirator', category: 'Safety', unit: 'Each', defaultCost: 35, isActive: true },
  { name: 'Hard Hat', category: 'Safety', unit: 'Each', defaultCost: 22, isActive: true },
  { name: 'High-Vis Safety Vest', category: 'Safety', unit: 'Each', defaultCost: 12, isActive: true },
  { name: 'First Aid Kit', category: 'Safety', unit: 'Each', defaultCost: 28, isActive: true },
  { name: 'Fire Extinguisher 5lb', category: 'Safety', unit: 'Each', defaultCost: 45, isActive: true },

  // MISCELLANEOUS
  { name: 'Permit Fee - Residential HVAC', category: 'Miscellaneous', unit: 'Each', defaultCost: 150, isActive: true },
  { name: 'Equipment Disposal Fee', category: 'Miscellaneous', unit: 'Each', defaultCost: 75, isActive: true },
  { name: 'Refrigerant Reclaim Fee', category: 'Miscellaneous', unit: 'Each', defaultCost: 45, isActive: true },
  { name: 'Crane/Lift Rental Half Day', category: 'Miscellaneous', unit: 'Each', defaultCost: 350, isActive: true },
  { name: 'Crane/Lift Rental Full Day', category: 'Miscellaneous', unit: 'Each', defaultCost: 600, isActive: true },
  { name: 'Dumpster Rental', category: 'Miscellaneous', unit: 'Each', defaultCost: 250, isActive: true },
  { name: 'Copper Scrap Credit (per lb)', category: 'Miscellaneous', unit: 'Each', defaultCost: -3, isActive: true },
  { name: 'Miscellaneous Hardware Allowance', category: 'Miscellaneous', unit: 'Each', defaultCost: 25, isActive: true },
  { name: 'Shop Supplies Allowance', category: 'Miscellaneous', unit: 'Each', defaultCost: 35, isActive: true },
  { name: 'Fuel Surcharge', category: 'Miscellaneous', unit: 'Each', defaultCost: 25, isActive: true },
];